spring:
  application:
    name: spring-batch-migration

  # MongoDB configuration
  data:
    mongodb:
      # Default configuration for MongoDB without authentication
      uri: mongodb://localhost:27017/library
      
      # Alternative: Individual settings (comment out uri above if using these)
      # host: localhost
      # port: 27017
      # database: library
      
      # For MongoDB with authentication, replace uri above with:
      # uri: mongodb://username:password@localhost:27017/library?authSource=admin

  # JPA/H2 configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

  # Shell configuration
  shell:
    interactive:
      enabled: true

logging:
  level:
    org.springframework.batch: DEBUG
    ru.otus.hw: DEBUG