name: Build

on:
  pull_request:

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Checkstyle check
        run: |
          mvn checkstyle:check --no-transfer-progress

      - name: Run tests
        run: |
          mvn test --no-transfer-progress
        env:
          CI: true
          SPRING_DATA_MONGODB_DATABASE: test
          DE_FLAPDOODLE_MONGODB_EMBEDDED_VERSION: 4.0.2
          SPRING_MONGODB_EMBEDDED_VERSION: 4.0.2

      - name: Build application
        run: |
          mvn verify --no-transfer-progress
