name: Build

on:
  pull_request:

jobs:
  build-app:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.0.2
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Checkstyle check
        run: |
          mvn checkstyle:check --no-transfer-progress

      - name: Run tests
        run: |
          mvn test --no-transfer-progress
        env:
          SPRING_DATA_MONGODB_HOST: localhost
          SPRING_DATA_MONGODB_PORT: 27017
          SPRING_DATA_MONGODB_DATABASE: test
          SPRING_DATA_MONGODB_USERNAME: root
          SPRING_DATA_MONGODB_PASSWORD: example
          SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
          DE_FLAPDOODLE_MONGODB_EMBEDDED_VERSION: 4.0.2
          SPRING_MONGODB_EMBEDDED_VERSION: 4.0.2

      - name: Build application
        run: |
          mvn verify --no-transfer-progress
